# Generated by Django 5.1.2 on 2024-11-16 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='testresults',
            name='image',
            field=models.ImageField(default='generated_answer_sheet.png', upload_to=''),
            preserve_default=False,
        ),
    ]
